---
- name: Install nfs-common
  apt: name=nfs-common

# Mount on all devices - not all are accessible to all devices
- name: Ensure directories exist
  file: path={{item}} state=directory
  with_items:
  - /mnt/mediawiki/uploads
  - /mnt/mediawiki/private/uploads
  
- name: Mount public uploads
  mount: name=/mnt/mediawiki/uploads fstype=nfs src=10.131.243.247:/var/mediawiki/uploads state=mounted
  sudo: yes
  sudo_user: mediawiki
  
- name: Mount private uploads
  mount: name=/mnt/mediawiki/private/uploads fstype=nfs src=10.131.243.247:/var/mediawiki/private/uploads state=mounted
  sudo: yes
  sudo_user: mediawiki
