- name: Clear APC cache
  command: /usr/bin/wget -qO- {{apc_clear_script}}
  register: clear_apc_cache
  failed_when: clear_apc_cache.stdout.find('true') == -1

- name: Rebuild localisation cache
  command: /usr/bin/php /usr/share/nginx/.orain.org/w/maintenance/rebuildLocalisationCache.php --wiki extloadwiki

- name: Install Validator dependencies using Composer
  shell: "cd /usr/share/nginx/.orain.org/w/extensions/Validator && /usr/bin/composer.phar install"

- name: Notify IRC of Mediawiki update
  shell: "/root/notify_irc.sh"
