- include: packages.yml
- include: files.yml

- name: Disable MySQLi
  lineinfile: dest=/etc/php5/fpm/conf.d/20-mysqli.ini regexp='^;?extension\=mysqli\.so' line=';extension=mysqli.so'
  notify: Reload php-fpm
  # 20-mysqli.ini might not exist
  ignore_errors: yes
