---
- name: Create user "www-scripts"
  user: name=www-scripts group=www-data shell=/bin/zsh

- name: Install python-requests
  apt: pkg=python3-requests

- name: Check out latest stable WMF branch of MediaWiki
  git: repo=https://github.com/Orain/mediawiki-core.git
       dest=/usr/share/nginx/.orain.org/w
       version=REL1_22
  notify:
    - Clear APC cache
    - Rebuild localisation cache
    - Mediawiki submodule fileMode false
    - Notify IRC of Mediawiki update

- name: Install Composer
  action: shell curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin/ creates=/usr/bin/composer.phar

- name: Update Composer
  action: shell /usr/bin/composer.phar self-update
  register: composer_update_output
  changed_when: composer_update_output.stdout.find('You are already using composer version') == -1

- name: Validate LocalSettings
  shell: php -l /root/ansible-playbook/roles/mediawiki/files/LocalSettings.php.j2
  register: mw_localsettings_valid
  failed_when: mw_localsettings_valid.rc != 0
  changed_when: False

- name: Copy MediaWiki settings from templates
  template: src={{item}} dest=/usr/share/nginx/.orain.org/w/{{item|basename|replace('.j2','')}} backup=yes
  with_fileglob:
    - ./*.php.j2
  notify:
    - Clear APC cache
    - Rebuild localisation cache
    - Notify IRC of Mediawiki update
  when: mw_localsettings_valid.rc == 0

- name: Copy MediaWiki settings from files
  copy: src={{item}} dest=/usr/share/nginx/.orain.org/w/{{item|basename}} backup=yes
  with_fileglob:
    - ./*.php
  notify: Clear APC cache

- name: Copy {{item}}
  copy: src={{item}} dest=/home/www-scripts owner=www-scripts group=www-data mode=770 backup=yes
  with_items:
    - get_db_list.py
    - db_loop.sh

- name: Copy logrotate configuration
  copy: src="./logrotate.d/mediawiki" dest=/etc/logrotate.d

- name: Copy IRC notification script
  copy: src="./notify_irc.sh" dest=/root/notify_irc.sh owner=root group=root mode=775

- name: Create a cronjob for get_db_list.py
  cron: name="Get DB list" user="www-scripts" job="python3 ~/get_db_list.py"

- name: Create a cronjob for the MediaWiki job queue
  cron: name="MediaWiki job queue"
        user="www-scripts"
        minute=0
        job="/home/www-scripts/db_loop.sh /usr/share/nginx/.orain.org/w/maintenance/runJobs.php > /var/log/mediawiki/runJobs.log 2>&1"

- name: Create a cronjob for MediaWiki special page updating on All The Tropes
  cron: name="MediaWiki special page updating"
        user="www-scripts"
        minute="0"
        hour="*/3"
        job="/usr/bin/php /usr/share/nginx/.orain.org/w/maintenance/updateSpecialPages.php --wiki allthetropeswiki > /var/log/mediawiki/updateSpecialPages.log 2>&1"

- name: Copy quickscripts
  copy: src={{item}} dest=/root/{{item|basename}} owner=root group=root mode=770
  with_fileglob:
    - ./quickscripts/*
