- name: Install python-requests
  apt: pkg=python3-requests

- name: Install Composer
  action: shell curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin/ creates=/usr/local/bin/composer.phar

# Removed on 31 August 2014 - Addshore - Location changed
- name: Remove old Composer install at /usr/bin/composer.phar
  command: rm /usr/bin/composer.phar removes=/usr/bin/composer.phar

# Fail ansible because of HHVM
#- name: Update Composer
#  action: shell /usr/local/bin/composer.phar self-update
#  register: composer_update_output
#  changed_when: composer_update_output.stdout.find('You are already using composer version') == -1

- name: Install Lua 5.1
  apt: pkg=liblua5.1-0
  
  # wget until we decide to set up an apt-repo. {{item}} because we have a few of these but only one exists right now
- name: wget Orain deb packages
  shell: wget apt.orain.org/ubuntu/{{item}}
  with_items:
  - php5-redis.deb
  args:
    chdir: /root/debs/
    creates: /root/debs/{{item}}
  changed_when: False # never report as changed
  
- name: Install Orain deb packages
  apt: deb={{item}}
  with_items:
  - /root/debs/php5-redis.deb
  failed_when: False # never report as changed

- name: Create /srv/mediawiki
  file: path=/srv/mediawiki state=directory owner=mediawiki

- name: Check out latest stable WMF branch of MediaWiki
  git: repo=https://github.com/Orain/mediawiki-core.git
       dest=/srv/mediawiki/w
       version=REL1_23
  sudo: yes
  sudo_user: mediawiki
  notify:
    - Rebuild localisation cache
    - Update mediawiki
    - Mediawiki submodule fileMode false

- name: Check out extensions for MediaWiki
  git: repo={{item.repo}}
       dest=srv/mediawiki/w/{{item.dest}}
       version={{item.version}}
  with_items: extensions
  sudo: yes
  sudo_user: mediawiki
  tags:
    - slow
    - mwext
  notify:
    - Rebuild localisation cache
    - Update mediawiki
    - Mediawiki submodule fileMode false


- name: Check out skins for MediaWiki
  git: repo={{item.repo}}
       dest=/srv/mediawiki/w/{{item.dest}}
       version={{item.version}}
  with_items: skins
  sudo: yes
  sudo_user: mediawiki
  tags:
    - slow
    - mwskin
  notify:
    - Mediawiki submodule fileMode false
